# allows Ctrl+S to save on vim
stty ixany
stty ixoff -ixon
stty stop undef
stty start undef

# Only "exit" or "logout" will log off the system.
# set -o ignoreeof

#Set up text editing/viewing.
export LANG=en_US.utf-8
export CLICOLOR=1 #Colorizes output of ls and others.
export EDITOR=vi
export VISUAL=$EDITOR
export PAGER=less
# export LESS='-i-P%f (%i/%m) Line %lt/%L' #Better prompt, case-insensitive search by default.

TERM=screen-256color

export ENV=$HOME/.bashrc

# Set up command history.
export HISTSIZE=100000
export HISTFILESIZE=100000

# Make shells write to history immediately instead of on exit.
shopt -s histappend
export PROMPT_COMMAND='history -a'

#Functions.
function gitrm {
    git status | grep 'deleted' | awk '{print $3}' | xargs git rm
}
function toss {
    for filename; do
        if [ -e $HOME/.Trash/$filename ]; then
            mv "${filename}" "${HOME}/.Trash/${filename}$(date +%Y%m%d%H%M%S)"
        else
            mv "${filename}" "${HOME}/.Trash"
        fi
    done
}
function my_ip {
    ifconfig | grep 'broadcast' | awk '{print $6}'
}
function variables() {
  comm -23 <(declare) <(declare -f) ;
}


#The command line prompt.
case "$TERM" in
    xterm) color_prompt=yes;;
    xterm-color) color_prompt=yes;;
    xterm-256color) color_prompt=yes;;
    screen-256color) color_prompt=yes;;
esac

source ~/.dotfiles/git/git-prompt.sh
source ~/.dotfiles/shells/configs.sh

if [ "$color_prompt" = yes ]; then
    # export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\n\[\033[00m\]\$ ' #No date
    # export PS1="\[\033[01;32m\][\$(date +%Y%m%d_%H%M%S)] \u@\h\[\033[00m\]:\[\033[01;34m\]\w\n\[\033[00m\]\$ "
    #source /etc/bash_completion.d/git
    export PS1="\[\033[01;32m\][\$(date +%Y%m%d_%H%M%S)] \u@\h\[\033[00m\]:\[\033[01;34m\]\w\033[01;31m \$(__git_ps1 \"(%s)\")\n\[\033[00m\]\$ "
else
    # export PS1='\u@\h:\w\n\$ ' #No date
    export PS1="[\$(date +%Y%m%d_%H%M%S)] \u@\h:\w\n\$ "
fi

#Keep this last so it can override general settings!
if [ -f $HOME/.bashrc.local ]; then
    source $HOME/.bashrc.local
fi

#Set starting directory.
# cd ~/Projects

#Set up fasd.
#eval "$(fasd --init auto)"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="${SDKMAN_DIR:-$HOME/.sdkman}"
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# added by Miniconda3 4.3.11 installer
# export PATH="$HOME/miniconda3/bin:$PATH"  # commented out by conda initialize

# added by Miniconda3 installer
# export PATH="/Users/heuert/miniconda3/bin:$PATH"  # commented out by conda initialize
###-tns-completion-start-###
if [ -f "$HOME/.tnsrc" ]; then
    source "$HOME/.tnsrc"
fi
###-tns-completion-end-###
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('$HOME/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

[ -r "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
for env_file in "$HOME/.env" "$HOME/.dotfiles/.env"; do
    if [ -r "$env_file" ]; then
        set -a
        . "$env_file"
        set +a
    fi
done
export FROGONE_PATH="${FROGONE_PATH:-$HOME/FrogOne}"
export PANELPC_IP="${PANELPC_IP:-}"
export PANELPC_HOST="${PANELPC_HOST:-$PANELPC_IP}"
if command -v brew >/dev/null 2>&1; then
    eval "$(brew shellenv)"
fi

# >>> Codex installer >>>
export PATH="$HOME/.local/bin:$PATH"
# <<< Codex installer <<<
