export LC_ALL=C
export LANG=C

# Restore MSYS2 core paths
export PATH="/usr/bin:/bin:$PATH"

DISABLE_AUTO_TITLE="true"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [[ -f "$HOME/.env" ]]; then
  if [[ -o allexport ]]; then
    source "$HOME/.env"
  else
    set -a
    source "$HOME/.env"
    set +a
  fi
fi

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="candy"
# ZSH_THEME="alanpeabody"
if [[ -r "$ZSH/custom/themes/powerlevel10k/powerlevel10k.zsh-theme" ]]; then
  ZSH_THEME="powerlevel10k/powerlevel10k"
else
  # A clean built-in fallback when Powerlevel10k isn't installed yet.
  ZSH_THEME="robbyrussell"
fi
# ZSH_THEME="kphoen"
# ZSH_THEME="jreese"
# ZSH_THEME="juanghurtado"
#ZSH_THEME="kafeitu"

# ZSH_THEME="mortalscumbag" # tells when it is ssh
# ZSH_THEME="pygmalion"
# ZSH_THEME="tjkirch"
# ZSH_THEME="xiong-chiamiov-plus"


# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
#
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)

if [[ -r /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]]; then
  source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
elif [[ -r "$HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh" ]]; then
  source "$HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"
elif [[ -r "$HOME/.zsh/zsh-autosuggestions/autosuggestions.zsh" ]]; then
  source "$HOME/.zsh/zsh-autosuggestions/autosuggestions.zsh"
fi
plugins=(git gitfast git-extras debian bundler composer gitfast urltools web-search vi-mode docker docker-compose wd node jsontools gitignore gradle magic-enter)
#plugins=(debian bundler composer urltools web-search vi-mode docker docker-compose wd node jsontools gitignore gradle magic-enter)

if [[ -r "$ZSH/oh-my-zsh.sh" ]]; then
  source "$ZSH/oh-my-zsh.sh"
else
  # Dependency-free prompt: user@host, working directory, and prompt marker.
  autoload -Uz colors && colors
  PROMPT='%F{green}%n@%m%f %F{blue}%~%f %(?.%F{green}.%F{red})❯%f '
fi

# save a ton of history
HISTSIZE=20000
HISTFILE=~/.zsh_history
SAVEHIST=20000

LANG=en_US.utf-8
LANGUAGE=en
CLICOLOR=1 #Colorizes output of ls and others.
EDITOR=nvim
VISUAL=$EDITOR
PAGER=less
LESS='-R -g -w'

# disable flow control commands (keeps C-s from freezing everything)
#stty start undef
#stty stop undef
if [[ -o interactive ]] && [[ -t 0 ]]; then
  stty -ixon
fi

source ~/.dotfiles/shells/rvm.sh
source ~/.dotfiles/shells/configs.sh
source ~/.dotfiles/shells/zsh/functions.zsh
# source ~/.dotfiles/shells/zsh/autosuggestions.zsh

if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi

# Always work in a tmux session if tmux is installed
if which tmux 2>&1 >/dev/null; then
  if [ $TERM != "screen-256color"  ] && [ $TERM != "screen"  ]; then
    # tmux attach -t hack || tmux new -s hack; exit
  fi
fi

# disable gnome effects
which ggsettings > /dev/null 2>&1 && set org.gnome.desktop.interface enable-animations false
#which rbenv > /dev/null 2>&1 && eval "$(rbenv init - --no-rehash zsh)"

# example-user:

# Bind the reverse search to ctrl + R
bindkey -v
bindkey '\e[3~' delete-char
#bindkey '^R' history-incremental-search-backwardl-search-backward

bindkey '^U' backward-kill-line
bindkey '^Y' yank
bindkey ^H vi-backward-word
bindkey ^L vi-forward-word

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh"  ] && . "$NVM_DIR/nvm.sh" # This loads nvm
# place this after nvm initialization!
autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}

#export NODE_PATH=`which node`
#nvm use stable


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# The next line updates PATH for the Google Cloud SDK.
if [ -f $HOME/google-cloud-sdk/path.zsh.inc ]; then
  source "$HOME/google-cloud-sdk/path.zsh.inc"
fi

# The next line enables shell command completion for gcloud.
if [ -f $HOME/google-cloud-sdk/completion.zsh.inc ]; then
  source "$HOME/google-cloud-sdk/completion.zsh.inc"
fi

###-tns-completion-start-###
if [ -f ~/.tnsrc ]; then
    source ~/.tnsrc
fi
###-tns-completion-end-###
export PATH=~/apache-maven/bin:$PATH
export PATH=~/.dotfiles/vim/bundle/phpctags/bin:$PATH

###-tns-completion-start-###
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/miniconda3/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

if [ -d /home/linuxbrew/.linuxbrew/bin ]; then
	export PATH=$PATH:/home/linuxbrew/.linuxbrew/bin
fi
. ~/.dotfiles/shells/powerline.zshrc

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
alias sail="vendor/bin/sail"
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$ANDROID_HOME/emulator:$PATH
export PATH=$ANDROID_HOME/platform-tools:$PATH
# eval $(ssh-agent) # do not add this if using KDE wallet to manage keys!
# export PATH=$PATH:~/idea/idea-IU-223.8617.56/bin


# Load Angular CLI autocompletion.
#source <(ng completion script)

export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$ANDROID_HOME/emulator:$PATH
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$HOME/.local/bin:$PATH
#eval $(thefuck --alias)


# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# Let the desktop session or keychain manage ssh-agent. Starting an agent here
# makes every new terminal prompt for a key and can leave orphaned processes.

export LC_ALL=C.UTF-8
export LANG=C.UTF-8
#export FROGONE_PATH=/mnt/c/Users/ExampleUser/projects/linux/FrogOne
export FROGONE_PATH=~/FrogOne
#export PANELPC_IP=example-host
export PANELPC_IP=192.0.2.162
#export PANELPC_HOST=example-host
export PANELPC_HOST=192.0.2.162
export PATH=~/bin:$PATH
export DL=/mnt/c/Users/ExampleUser/Downloads
export F=/mnt/c/Users/ExampleUser/projects/linux/FrogOne


command -v brew >/dev/null 2>&1 && eval "$(brew shellenv)"
command -v fzf >/dev/null 2>&1 && source <(fzf --zsh)

DISABLE_UNTRACKED_FILES_DIRTY=true

export PATH="$HOME/.nimble/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/share/bob/nvim-bin:$PATH"

command -v mise >/dev/null 2>&1 && eval "$(mise activate zsh)"

# ASP.NET Core HTTPS dev cert (OpenSSL / curl / HttpClient)
export SSL_CERT_DIR="$HOME/.aspnet/dev-certs/trust:${SSL_CERT_DIR:-/etc/ssl/certs}"
