# Use a modern terminal type
set -g default-terminal "tmux-256color"

# True color support
set -as terminal-features ",xterm-256color:RGB"

# Sensible responsiveness
set -sg escape-time 10

# Mouse support
set -g mouse on

# Start windows/panes at 1
set -g base-index 1
setw -g pane-base-index 1

# Easier reload
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Better splits
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

# Vim-like pane movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim-like pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Keep copy mode in vi style
setw -g mode-keys vi

# Make cursor behave better with terminal + Neovim
set -g terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[2 q'

# Clipboard integration
set -g set-clipboard on


# Wayland
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"

# X Clipboard
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -i"

unbind C-b
set -g prefix C-a
bind C-a send-prefix
